apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::{{REPLACE-WITH-YOUR-AWS-ACCOUNT-ID}}:role/node-group-1-eks-node-group-20240311023415265300000002
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - eks:readonly
      rolearn: arn:aws:iam::{{REPLACE-WITH-YOUR-AWS-ACCOUNT-ID}}:role/eks-read-only
      username: eks-read-only
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
